python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v2_c3_sim/0/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_sil_t2000_sim0/ckpts --ckptfile experiments/directed_kmeans_sil_t2000_sim0/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v2_c3/kmeans_sil_t2000/

python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v2_c3_sim/0.3/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_sil_t2000_sim03/ckpts --ckptfile experiments/directed_kmeans_sil_t2000_sim03/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v2_c3/kmeans_sil_t2000/

python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v2_c3_sim/0.5/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_sil_t2000_sim05/ckpts --ckptfile experiments/directed_kmeans_sil_t2000_sim05/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v2_c3/kmeans_sil_t2000/

python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v2_c3_sim/0.7/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_sil_t2000_sim07/ckpts --ckptfile experiments/directed_kmeans_sil_t2000_sim07/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v2_c3/kmeans_sil_t2000/

python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v2_c2_sim/0/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_sil_c2_t2000_sim0/ckpts --ckptfile experiments/directed_kmeans_sil_c2_t2000_sim0/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v2_c2/kmeans_sil_t2000/

python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v2_c2_sim/0.3/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_sil_c2_t2000_sim0.3/ckpts --ckptfile experiments/directed_kmeans_sil_c2_t2000_sim0.3/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v2_c2/kmeans_sil_t2000/

python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v2_c2_sim/0.5/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_sil_c2_t2000_sim0.5/ckpts --ckptfile experiments/directed_kmeans_sil_c2_t2000_sim0.5/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v2_c2/kmeans_sil_t2000/

python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v2_c2_sim/0.7/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_sil_c2_t2000_sim0.7/ckpts --ckptfile experiments/directed_kmeans_sil_c2_t2000_sim0.7/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v2_c2/kmeans_sil_t2000/

python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v3_c2_sim/0/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_v3_sil_c2_t2000_sim0/ckpts --ckptfile experiments/directed_kmeans_v3_sil_c2_t2000_sim0/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v3_c2/kmeans_sil_t2000/

python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v3_c2_sim/0.3/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_v3_sil_c2_t2000_sim0.3/ckpts --ckptfile experiments/directed_kmeans_v3_sil_c2_t2000_sim0.3/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v3_c2/kmeans_sil_t2000/

python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v3_c2_sim/0.5/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_v3_sil_c2_t2000_sim0.5/ckpts --ckptfile experiments/directed_kmeans_v3_sil_c2_t2000_sim0.5/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v3_c2/kmeans_sil_t2000/

python gate/network/edge_directed_kmeans_node/inference.py --outdir dataset/CASP15_inhouse/server_dataset/processed_dataset_directed_kmeans_v3_c2_sim/0.7/kmeans_sil_t2000/ --ckptdir experiments/directed_kmeans_v3_sil_c2_t2000_sim0.7/ckpts --ckptfile experiments/directed_kmeans_v3_sil_c2_t2000_sim0.7/best_ckpts.txt --datadir dataset/CASP15_inhouse/server_dataset/sample/kmeans_v3_c2/kmeans_sil_t2000/