python gate/network/edge_directed_kmeans_node/train_single_fold_seed_v3_af_mango.py --datadir dataset/CASP15_inhouse_full/sample/kmeans_v6/kmeans_sil_t3000/ --scoredir dataset/CASP15_inhouse_full/ --outdir dataset/CASP15_inhouse_full/processed_dataset_directed_kmeans_v6/0.5/kmeans_sil_t3000/ --fold 0 --project directed_kmeans_af_v6_t3000_sim0.5 --dbdir experiments/ --labeldir dataset/CASP15_inhouse_full/label/ --log_val_mse true

#python gate/network/edge_directed_kmeans_node/train_single_fold_seed_v3_af_mango.py --datadir dataset/CASP15_inhouse_full/sample/kmeans_v6/kmeans_sil_t3000/ --scoredir dataset/CASP15_inhouse_full/ --outdir dataset/CASP15_inhouse_full/processed_dataset_directed_kmeans_v6/0.5/kmeans_sil_t3000/ --fold 1 --project directed_kmeans_af_v6_t3000_sim0.5 --dbdir experiments/ --labeldir dataset/CASP15_inhouse_full/label/ --log_val_mse true

python gate/network/edge_directed_kmeans_node/train_single_fold_seed_v3_af_mango.py --datadir dataset/CASP15_inhouse_full/sample/kmeans_v6/kmeans_sil_t3000/ --scoredir dataset/CASP15_inhouse_full/ --outdir dataset/CASP15_inhouse_full/processed_dataset_directed_kmeans_v6/0.5/kmeans_sil_t3000/ --fold 2 --project directed_kmeans_af_v6_t3000_sim0.5 --dbdir experiments/ --labeldir dataset/CASP15_inhouse_full/label/ --log_val_mse true

python gate/network/edge_directed_kmeans_node/train_single_fold_seed_v3_af_mango.py --datadir dataset/CASP15_inhouse_full/sample/kmeans_v6/kmeans_sil_t3000/ --scoredir dataset/CASP15_inhouse_full/ --outdir dataset/CASP15_inhouse_full/processed_dataset_directed_kmeans_v6/0.5/kmeans_sil_t3000/ --fold 3 --project directed_kmeans_af_v6_t3000_sim0.5 --dbdir experiments/ --labeldir dataset/CASP15_inhouse_full/label/ --log_val_mse true

python gate/network/edge_directed_kmeans_node/train_single_fold_seed_v3_af_mango.py --datadir dataset/CASP15_inhouse_full/sample/kmeans_v6/kmeans_sil_t3000/ --scoredir dataset/CASP15_inhouse_full/ --outdir dataset/CASP15_inhouse_full/processed_dataset_directed_kmeans_v6/0.5/kmeans_sil_t3000/ --fold 4 --project directed_kmeans_af_v6_t3000_sim0.5 --dbdir experiments/ --labeldir dataset/CASP15_inhouse_full/label/ --log_val_mse true

python gate/network/edge_directed_kmeans_node/train_single_fold_seed_v3_af_mango.py --datadir dataset/CASP15_inhouse_full/sample/kmeans_v6/kmeans_sil_t3000/ --scoredir dataset/CASP15_inhouse_full/ --outdir dataset/CASP15_inhouse_full/processed_dataset_directed_kmeans_v6/0.5/kmeans_sil_t3000/ --fold 5 --project directed_kmeans_af_v6_t3000_sim0.5 --dbdir experiments/ --labeldir dataset/CASP15_inhouse_full/label/ --log_val_mse true

python gate/network/edge_directed_kmeans_node/train_single_fold_seed_v3_af_mango.py --datadir dataset/CASP15_inhouse_full/sample/kmeans_v6/kmeans_sil_t3000/ --scoredir dataset/CASP15_inhouse_full/ --outdir dataset/CASP15_inhouse_full/processed_dataset_directed_kmeans_v6/0.5/kmeans_sil_t3000/ --fold 6 --project directed_kmeans_af_v6_t3000_sim0.5 --dbdir experiments/ --labeldir dataset/CASP15_inhouse_full/label/ --log_val_mse true

python gate/network/edge_directed_kmeans_node/train_single_fold_seed_v3_af_mango.py --datadir dataset/CASP15_inhouse_full/sample/kmeans_v6/kmeans_sil_t3000/ --scoredir dataset/CASP15_inhouse_full/ --outdir dataset/CASP15_inhouse_full/processed_dataset_directed_kmeans_v6/0.5/kmeans_sil_t3000/ --fold 7 --project directed_kmeans_af_v6_t3000_sim0.5 --dbdir experiments/ --labeldir dataset/CASP15_inhouse_full/label/ --log_val_mse true

python gate/network/edge_directed_kmeans_node/train_single_fold_seed_v3_af_mango.py --datadir dataset/CASP15_inhouse_full/sample/kmeans_v6/kmeans_sil_t3000/ --scoredir dataset/CASP15_inhouse_full/ --outdir dataset/CASP15_inhouse_full/processed_dataset_directed_kmeans_v6/0.5/kmeans_sil_t3000/ --fold 8 --project directed_kmeans_af_v6_t3000_sim0.5 --dbdir experiments/ --labeldir dataset/CASP15_inhouse_full/label/ --log_val_mse true

python gate/network/edge_directed_kmeans_node/train_single_fold_seed_v3_af_mango.py --datadir dataset/CASP15_inhouse_full/sample/kmeans_v6/kmeans_sil_t3000/ --scoredir dataset/CASP15_inhouse_full/ --outdir dataset/CASP15_inhouse_full/processed_dataset_directed_kmeans_v6/0.5/kmeans_sil_t3000/ --fold 9 --project directed_kmeans_af_v6_t3000_sim0.5 --dbdir experiments/ --labeldir dataset/CASP15_inhouse_full/label/ --log_val_mse true
