apiVersion: v1
kind: Pod
metadata:
  name: jl4mc-data-transfer-gpu-pod-pvc
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-central
  containers:
  - command:
    - sh
    - -c
    - echo 'I am a new pod for data transfers to one of my PVCs' && sleep infinity
    image: ubuntu:20.04
    name: jl4mc-data-transfer-pod-pvc
    resources:
      limits:
        cpu: 2
        memory: 12Gi
        nvidia.com/gpu: 1
      requests:
        cpu: 2
        memory: 10Gi
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /data
      name: jl4mc-bml-casp15-pvc
  volumes:
  - name: jl4mc-bml-casp15-pvc
    persistentVolumeClaim:
      claimName: jl4mc-bml-casp15-pvc
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      # note: here, we are asking for 24GB GPUs only
                      - NVIDIA-A10
                      - NVIDIA-GeForce-RTX-3090
                      - NVIDIA-TITAN-RTX
                      - NVIDIA-RTX-A5000
                      - Quadro-RTX-6000
