apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jl4mc-gate-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  storageClassName: rook-cephfs-central
